# Generated by Django 6.0.5 on 2026-05-22 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('problems', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_difficulty', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('was_accepted', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.user')),
            ],
            options={
                'db_table': 'difficulty_recommendations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_score', models.FloatField(default=0.5)),
                ('problems_attempted', models.PositiveIntegerField(default=0)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('avg_attempts_to_solve', models.FloatField(default=0)),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profiles', to='users.user')),
            ],
            options={
                'db_table': 'user_skill_profiles',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('user', 'category')},
            },
        ),
    ]
