databases:
  - name: algonext-db
    databaseName: algonext
    user: algonext_user
    plan: free

services:
  - type: redis
    name: algonext-redis
    plan: free
    ipAllowList: [] # only allow internal connections

  - type: web
    name: algonext-api
    env: python
    buildCommand: "cd backend && chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && honcho start"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: algonext-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: algonext-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: algonext-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: algonext-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "algonext.settings.production"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
