# Generated by Django 6.0.5 on 2026-05-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='custom_input',
            field=models.TextField(blank=True),
        ),
    ]
